'use client'
import { useCallback, useEffect, useState } from 'react'

type Field={id:string;label:string;helpText?:string;type:string;options?:string;required?:boolean;active?:boolean}
type Section={title:string;repeatable?:boolean;fields:Field[]}
const key=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')
const endpoint='/api/research-portal'
export function ResearchPortal({token}:{token:string}){
 const [state,setState]=useState<any>(null),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[idx,setIdx]=useState(0),[answers,setAnswers]=useState<any>({}),[declared,setDeclared]=useState(false),[savedAt,setSavedAt]=useState(''),[sent,setSent]=useState(false),[dirty,setDirty]=useState(false)
 const load=useCallback(async()=>{const r=await fetch(`${endpoint}?action=state`,{cache:'no-store'});const d=await r.json();setState(d);if(d.authenticated){setAnswers(d.submission.answers||{});setDeclared(Boolean(d.submission.submittedAt))}},[])
 useEffect(()=>{(async()=>{if(token){setBusy(true);const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'redeem',token})});const d=await r.json();if(!r.ok)setMessage(d.error||'This link is invalid or expired.');else history.replaceState({},'', '/research-portal');setBusy(false)}await load()})()},[token,load])
 useEffect(()=>{if(!state?.authenticated||state.submission.status==='submitted'||state.submission.status==='under_review')return;const t=setTimeout(async()=>{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'save',answers})});const d=await r.json();if(r.ok){setSavedAt(new Date(d.savedAt).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}));setDirty(false)}},1200);return()=>clearTimeout(t)},[answers,state])
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty&&state?.authenticated&&!['submitted','under_review'].includes(state.submission.status)){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[state,dirty])
 const locked=['submitted','under_review'].includes(state?.submission?.status)
 const sections:Section[]=state?.settings?.sections||[]
 const update=(id:string,v:any,group?:string,row?:number)=>{setDirty(true);setAnswers((old:any)=>{const next={...old};if(group){const rows=[...(next[group]||[])];rows[row]={...(rows[row]||{}),[id]:v};next[group]=rows}else next[id]=v;return next})}
 const save=async()=>{setBusy(true);const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'save',answers})});const d=await r.json();if(r.ok){setDirty(false);setMessage('Progress saved.')}else setMessage(d.error);setBusy(false)}
 const submit=async()=>{setBusy(true);const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'submit',answers,declaration:declared})});const d=await r.json();if(r.ok){setSent(true);await load()}else setMessage(d.missing?`${d.error} ${d.missing.slice(0,8).join('; ')}`:d.error);setBusy(false)}
 const requestLink=async(e:any)=>{e.preventDefault();setBusy(true);const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'request-link',email})});const d=await r.json();setMessage(d.message||'Check your email.');setBusy(false)}
 const signout=async()=>{await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'signout'})});setState({...state,authenticated:false});setMessage('You have signed out.')}
 if(!state)return <div className="container max-w-3xl py-16">Loading research portal…</div>
 if(!state.authenticated)return <div className="container max-w-xl py-16"><p className="text-xs font-semibold uppercase tracking-widest text-green">Nigeria Lex · Pilot 2026</p><h1 className="mt-3 font-serif text-3xl text-navy">Research Portal</h1><p className="mt-4 text-sm leading-6 text-slate">This secure portal is for law firms invited to complete the Nigeria Lex Pilot Study questionnaire. {state.open?'The submission window is open.':`The submission window is currently closed.`}</p><form onSubmit={requestLink} className="mt-8 space-y-4"><label className="block text-sm font-medium">Invited contact email<input required type="email" autoComplete="email" className="mt-2 w-full border border-line p-3" value={email} onChange={e=>setEmail(e.target.value)}/></label><button disabled={busy} className="bg-green px-5 py-3 text-sm font-semibold text-white">Email me a sign-in link</button></form>{message&&<p className="mt-4 text-sm text-slate">{message}</p>}<p className="mt-8 border-t border-line pt-5 text-xs leading-5 text-slate">{state.privacyNotice}</p></div>
 const sec=sections[idx];const group=sec?(sec as any).id||key(sec.title):'';const fields=(sec?.fields||[]).filter(f=>f.active!==false);const rows=sec?.repeatable?(answers[group]||[{}]):[answers]
 return <div className="container max-w-5xl py-12"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-green">Nigeria Lex · Pilot Study 2026</p><h1 className="mt-2 font-serif text-3xl text-navy">{state.participant.firmName}</h1><p className="mt-2 text-sm text-slate">{state.submission.reference} · {state.submission.status.replaceAll('_',' ')}</p></div><button onClick={signout} className="border border-line px-4 py-2 text-sm">Sign out</button></div>
 {state.submission.reopenReason&&<p className="mt-6 border-l-4 border-amber-500 bg-amber-50 p-4 text-sm">Changes requested: {state.submission.reopenReason}</p>}
 {locked?<div className="mt-8 rounded border border-line bg-white p-6"><h2 className="font-serif text-2xl text-navy">Submission received</h2><p className="mt-3 text-sm">Reference <strong>{state.submission.reference}</strong>. Your questionnaire is locked. Contact Nigeria Lex if a correction is needed.</p></div>:<>
 <div className="mt-8"><div className="h-2 bg-mist"><div className="h-2 bg-green transition-all" style={{width:`${state.submission.progress||0}%`}}/></div><div className="mt-3 flex justify-between text-xs text-slate"><span>Section {idx+1} of {sections.length}</span><span>{savedAt?`Saved at ${savedAt}`:'Changes save automatically'}</span></div></div>
 <nav className="mt-6 flex flex-wrap gap-2">{sections.map((s,i)=><button key={s.title} onClick={()=>setIdx(i)} className={`border px-3 py-2 text-xs ${i===idx?'border-navy bg-navy text-white':'border-line text-slate'}`}>{i+1}. {s.title}</button>)}<button onClick={()=>setIdx(sections.length)} className={`border px-3 py-2 text-xs ${idx===sections.length?'border-navy bg-navy text-white':'border-line text-slate'}`}>Review & Submit</button></nav>
 {sec?<section className="mt-6 rounded border border-line bg-white p-6"><h2 className="font-serif text-2xl text-navy">{sec.title}</h2>{sec.repeatable&&<p className="mt-2 text-sm text-slate">Add representative entries as needed. Answers remain saved even if an administrator later retires a field.</p>}<div className="mt-6 space-y-6">{rows.map((row:any,ri:number)=><div key={ri} className={sec.repeatable?'rounded border border-line p-5':''}><div className="grid gap-5 md:grid-cols-2">{fields.map(f=><FieldInput key={f.id} field={f} value={sec.repeatable?row[f.id]:answers[f.id]} disabled={locked} onChange={v=>update(f.id,v,sec.repeatable?group:undefined,sec.repeatable?ri:undefined)}/>)}</div>{sec.repeatable&&rows.length>1&&<button onClick={()=>{setDirty(true);setAnswers((old:any)=>({...old,[group]:old[group].filter((_:any,i:number)=>i!==ri)}))}} className="mt-4 text-sm text-red-700">Remove entry</button>}</div>)}</div>{sec.repeatable&&<button onClick={()=>{setDirty(true);setAnswers((old:any)=>({...old,[group]:[...(old[group]||[]),{}]}))}} className="mt-5 border border-green px-4 py-2 text-sm font-semibold text-green">+ Add {sec.title==='Representative Matters'?'representative matter':'practitioner'}</button>}</section>:<section className="mt-6 rounded border border-line bg-white p-6"><h2 className="font-serif text-2xl text-navy">Review & Submit</h2><p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate">{state.settings.privacyNotice}</p><div className="mt-6 space-y-4">{sections.map(s=><div key={s.title} className="border-t border-line pt-4"><h3 className="font-semibold text-navy">{s.title}</h3><pre className="mt-2 whitespace-pre-wrap break-words text-xs text-slate">{JSON.stringify(s.repeatable?answers[key(s.title)]||[]:Object.fromEntries((s.fields||[]).filter(f=>f.active!==false).map(f=>[f.label,answers[f.id]]).filter(([,v])=>v!==undefined)),null,2)}</pre></div>)}</div><label className="mt-6 flex gap-3 text-sm"><input type="checkbox" checked={declared} onChange={e=>setDeclared(e.target.checked)}/><span>{state.settings.consentText}</span></label><p className="mt-4 text-xs text-slate">Submission closes {new Date(state.settings.closesAt).toLocaleString('en-GB',{timeZone:'Africa/Lagos'})} WAT.</p><button onClick={submit} disabled={busy||!state.settings.open||!declared} className="mt-5 bg-green px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Submit final questionnaire</button></section>}
 <div className="mt-5 flex justify-between"><button disabled={idx===0} onClick={()=>setIdx(Math.max(0,idx-1))} className="border border-line px-4 py-2 text-sm disabled:opacity-40">Back</button><div className="flex gap-3"><button onClick={save} className="border border-line px-4 py-2 text-sm">Save now</button>{idx<sections.length&&<button onClick={()=>setIdx(idx+1)} className="bg-navy px-4 py-2 text-sm text-white">{idx===sections.length-1?'Review & Submit':'Next section'}</button>}</div></div></>}
 {state.settings.uploadsEnabled&&!locked&&<section className="mt-6 rounded border border-line bg-white p-6"><h2 className="font-serif text-xl text-navy">Supporting documents</h2><p className="mt-2 text-sm text-slate">PDF, Word, Excel, JPG or PNG; maximum 10 MB per file. Do not upload legally privileged or highly sensitive confidential information.</p><input className="mt-4 block text-sm" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);const fd=new FormData();fd.append('file',f);const r=await fetch('/api/research-portal/upload',{method:'POST',body:fd});const d=await r.json();setMessage(r.ok?`${f.name} uploaded.`:d.error);if(r.ok)await load();setBusy(false);e.target.value=''}}/><ul className="mt-4 space-y-2 text-sm">{(state.submission.documents||[]).map((f:any)=><li key={f.id}><a className="text-green underline" href={`/api/research-portal/download?id=${encodeURIComponent(f.id)}`}>{f.title}</a></li>)}</ul></section>}{message&&<p className="mt-4 text-sm text-red-700">{message}</p>}{sent&&<p className="mt-4 rounded bg-green-50 p-4 text-sm text-green-900">Submission received. A confirmation email has been sent.</p>}
 </div>
}
function FieldInput({field,value,onChange,disabled}:{field:Field;value:any;onChange:(x:any)=>void;disabled:boolean}){const common='mt-2 w-full border border-line bg-white p-3 text-sm';const opts=(field.options||'').split('|').filter(Boolean);const label=<span>{field.label}{field.required&&<b className="ml-1 text-red-700">*</b>}</span>;return <label className="block text-sm font-medium text-navy-ink">{label}{field.helpText&&<small className="mt-1 block font-normal text-slate">{field.helpText}</small>}{field.type==='textarea'?<textarea rows={4} required={field.required} disabled={disabled} className={common} value={value||''} onChange={e=>onChange(e.target.value)}/>:field.type==='select'?<select required={field.required} disabled={disabled} className={common} value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Choose…</option>{opts.map(o=><option key={o}>{o}</option>)}</select>:field.type==='multiselect'?<select multiple disabled={disabled} className={common} value={value||[]} onChange={e=>onChange(Array.from(e.target.selectedOptions).map(o=>o.value))}>{opts.map(o=><option key={o}>{o}</option>)}</select>:field.type==='checkbox'?<input type="checkbox" disabled={disabled} checked={Boolean(value)} onChange={e=>onChange(e.target.checked)} className="ml-3"/>:<input type={['text','email','number','date','url'].includes(field.type)?field.type:'text'} required={field.required} disabled={disabled} className={common} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
