import {NextRequest,NextResponse} from 'next/server'
import {createHash,timingSafeEqual,randomBytes,createCipheriv} from 'node:crypto'
import {gzipSync} from 'node:zlib'
import path from 'node:path'
import {readFile} from 'node:fs/promises'
import {S3Client,PutObjectCommand,GetObjectCommand,ListObjectsV2Command,DeleteObjectsCommand} from '@aws-sdk/client-s3'
import {getPayloadClient} from '@/lib/payload'
import {settings} from '@/lib/researchPortal'
import {logActivity} from '@/lib/activity'
export const dynamic='force-dynamic'
const match=(a:string,b:string)=>{if(!a||!b)return false;return timingSafeEqual(createHash('sha256').update(a).digest(),createHash('sha256').update(b).digest())}
async function all(payload:any,collection:string){const docs:any[]=[];let page=1,last=1;do{const r=await payload.find({collection,limit:1000,page,depth:0,overrideAccess:true});docs.push(...r.docs);last=r.totalPages;page++}while(page<=last);return docs}
export async function GET(req:NextRequest){if(!match(req.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||'',process.env.RESEARCH_CRON_SECRET||''))return NextResponse.json({error:'Unauthorized'},{status:401});const bucket=process.env.RESEARCH_BACKUP_BUCKET,key=process.env.RESEARCH_BACKUP_KEY;const access=process.env.RESEARCH_BACKUP_ACCESS_KEY_ID,secret=process.env.RESEARCH_BACKUP_SECRET_ACCESS_KEY;if(!bucket||!key||!access||!secret)return NextResponse.json({error:'Independent backup is not configured.'},{status:503});const encryptionKey=Buffer.from(key,'base64');if(encryptionKey.length!==32)return NextResponse.json({error:'RESEARCH_BACKUP_KEY must be base64 for exactly 32 bytes.'},{status:503});const payload=await getPayloadClient();const participants=await all(payload,'research-participants');const submissions=await all(payload,'research-portal-submissions');const documents=await all(payload,'research-documents');const files:any[]=[];for(const d of documents){try{let bytes:Buffer;if(process.env.MEDIA_STORAGE==='s3'||process.env.VERCEL){const source=new S3Client({region:process.env.S3_REGION||'us-east-1',endpoint:process.env.S3_ENDPOINT||undefined,forcePathStyle:process.env.S3_FORCE_PATH_STYLE==='true',credentials:{accessKeyId:process.env.S3_ACCESS_KEY_ID||'',secretAccessKey:process.env.S3_SECRET_ACCESS_KEY||''}});const result=await source.send(new GetObjectCommand({Bucket:process.env.S3_BUCKET,Key:`research/${d.filename}`}));bytes=Buffer.from(await result.Body!.transformToByteArray())}else bytes=await readFile(path.join(path.resolve(process.env.RESEARCH_UPLOAD_DIR||'storage/research'),path.basename(d.filename)));files.push({filename:d.filename,title:d.title,mimeType:d.mimeType,data:bytes.toString('base64')})}catch(error){payload.logger.error({err:error,msg:`Could not include research document ${d.filename} in backup`});return NextResponse.json({error:'Backup stopped because a supporting file could not be read.'},{status:500})}}
 const data={createdAt:new Date().toISOString(),participants,submissions,documents:documents.map(({filename,title,mimeType,filesize,participant,submission}:any)=>({filename,title,mimeType,filesize,participant,submission})),files,settings:await settings(payload)};const compressed=gzipSync(Buffer.from(JSON.stringify(data)));const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey,iv);const encrypted=Buffer.concat([Buffer.from('NLRS1'),iv,cipher.update(compressed),cipher.final(),cipher.getAuthTag()]);const s3=new S3Client({region:process.env.RESEARCH_BACKUP_REGION||process.env.S3_REGION||'us-east-1',endpoint:process.env.RESEARCH_BACKUP_ENDPOINT||undefined,forcePathStyle:process.env.RESEARCH_BACKUP_FORCE_PATH_STYLE!=='false',credentials:{accessKeyId:access,secretAccessKey:secret}});const stamp=new Date().toISOString().replace(/[:.]/g,'-');const objectKey=`nigeria-lex-research/${stamp}.nlbackup`;await s3.send(new PutObjectCommand({Bucket:bucket,Key:objectKey,Body:encrypted,ContentType:'application/octet-stream',Metadata:{encryption:'AES-256-GCM',format:'NLRS1'}}));await logActivity(payload,{action:'system',resourceType:'system',resource:'research-backup',resourceLabel:objectKey,summary:'Created encrypted research backup: '+participants.length+' firms, '+submissions.length+' submissions, '+files.length+' files'});return NextResponse.json({ok:true,key:objectKey,records:{participants:participants.length,submissions:submissions.length,files:files.length},encryptedBytes:encrypted.length})}