// This file is auto-generated by Payload. Do not edit it by hand.
// Run `npm run generate:importmap` after adding custom admin components
// to regenerate it. A fresh, empty map is valid for a project with no
// custom admin UI components yet.
export const importMap = {}
